<?php 
function wim2a_menu() {

	$items['wim2a/page1/%'] = array( 
	    'page callback' => 'wim2a_page1',
	    'access arguments' => array('access content'), 
	    'type' => MENU_CALLBACK, 
	); 
	
	
	$items['wim2a/monformulaire'] = array(  
		'title' => 'Mon Formulaire',  
		'page callback' => 'drupal_get_form',  
		'page arguments' => array('wim2a_monformulaire'),  
		'access callback' => true,  
		'type' => MENU_CALLBACK,
	);
	
	return $items; 
} 

function wim2a_page1($arg='none') 
{
	
	$outputs['arg'] = $arg;
	$outputs['request_uri'] = $_SERVER['REQUEST_URI'];
	$outputs['query_string'] = $_SERVER['QUERY_STRING'];
	$outputs['path_info'] = isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO'] 
	                                                       : 'non défini';
	$outputs['script_name'] = $_SERVER['SCRIPT_NAME'];
	$str = '';
	foreach($outputs as $key => $value) {
		 $str .= $key . '<br>' . $value . '<br><br>';
	}
	return $str;
}

function wim2a_monformulaire($form, &$form_state) {  

	$form['nom'] = array(  
		'#title' => 'Nom',
		'#type' => 'textfield',
	);
	$form['prenom'] = array(  
		'#title' => 'Prenom',
		'#type' => 'textfield',
	);
	
	$form['submit'] = array(  
		'#type' => 'submit',
		'#value' => t('Soumettre le formulaire!'),
	);
	return $form;
}

?>